apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: dragonfly-preheat
  labels:
    app: dragonfly-preheat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dragonfly-preheat
  template:
    metadata:
      labels:
        app: dragonfly-preheat
    spec:
      hostNetwork: true
      containers:
      - name: dragonfly-preheat
        image: registry.cn-zhangjiakou.aliyuncs.com/ringtail/dfclient:1.0.0-tuning
        restart: always
