apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: supernode
  labels:
    app: supernode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supernode
  template:
    metadata:
      labels:
        app: supernode
    spec:
      hostNetwork: true
      containers:
      - name: supernode
        image: registry.cn-zhangjiakou.aliyuncs.com/ringtail/supernode:1.0.0-tuning
        args:
        - '--max-bandwidth'
        - 6GB
        - '--up-limit'
        - '60'
        restart: always
        ports:
        - containerPort: 8081
        - containerPort: 8082
